basket/urls.py
from django.urls import path
from . import views
app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name="basket_add"),
    path('update/', views.basket_update, name="basket_update"),
    path('delete/', views.basket_delete, name="basket_delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# Project Base Import for URL Settings of MEDIA
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

# Project Base URL Settings of MEDIA
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category_list', kwargs={"category_slug": self.slug})


class ProductModelManager(models.Manager):
    def get_queryset(self):
        return super(ProductModelManager, self).get_queryset().filter(is_active=True)


class Product(models.Model):

    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductModelManager()

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from store.models import Product
from .basket import Basket

# Create your views here.


def basket_summary(request):
    return render(request, 'store/basket/summary.html', )


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        subtotal = basket.get_subtotal_price()
        total = basket.get_total_price()
        response = JsonResponse(
            {'qty': basketqty, 'subtotal': subtotal, 'total': total})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)
        basketqty = basket.__len__()
        subtotal = basket.get_subtotal_price()
        total = basket.get_total_price()
        response = JsonResponse(
            {'qty': basketqty, 'subtotal': subtotal, 'total': total})
        return response

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.


def products_all(request):
    products = Product.products.all()[0:6]
    context = {'products': products}
    return render(request, 'store/home.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {
        'product': product
    })


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {
        'category': category,
        'products': products
    })

templates/store/basket/summary.html
{% extends '../../base.html' %}

{% block title %}
  Basket Summary
{% endblock %}

{% block content %}
  <div class="container py-3">
    <div class="row">
      {% if basket %}
        <h1 id="basket_title" class="h5">Your Basket</h1>
        <p>
          Manage your <b>items</b> in your basket
        </p>
      {% else %}
        <h1 id="basket_title" class="h5">No Item Added on Basket</h1>
      {% endif %}
    </div>

    <div class="row bg-light p-3 d-flex justify-content-between">
      <div class="d-flex d-flex-inline">
        <div class="pe-3">Order</div>
        <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">Shipping options</a>

          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="dropdown-item small">
              <a class="text-decoration-none" href="#">Next day delivery</a>
            </li>
            <li class="dropdown-item small">
              <a class="text-decoration-none" href="#">Premimum delivery</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="text-end">
        <div class="pt-2">
          Sub Total: <span class="fw-bold h5">£</span><span id="subtotal" class="fw-bold h5">{{ basket.get_subtotal_price }}</span>
        </div>

        <div id="">
          Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">£11.50</span>
        </div>
        <div class="pt-2">
          Total to pay: <span class="fw-bold h4">£</span><span id="total" class="fw-bold h4">{{ basket.get_total_price }}</span>
        </div>
      </div>
    </div>

    <div class="row py-3">
      <div class="col-md-5 col-lg-4 text-end order-md-last order-2">
        <div class="d-grid gap-2">
          {% url 'payment:basket' as url_basket_payment %}
          <a role="button" href="{{ url_basket_payment }}" class="btn btn-success fw-bold" type="button">Checkout</a>
          <button class="btn btn-info" type="button">Save for later</button>
        </div>
      </div>

      <div class="col-md-7 col-lg-8 order-1">
        {% for item in basket %}
          {% with item.product as product %}
            <div data-index="{{ product.id }}" class="row mb-4 border product-item p-2">
              <div class="col-md-3 col-lg-2 order-md-first bg-light">
                <div class="card-img-top object-fit-contain overflow-hidden" style="height:125px">
                  <img class="mx-auto d-block" height="125px" width="120px" alt="Responsive image" src="{{ product.image.url }}" />
                </div>
              </div>
              <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10 p-2">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset"><h1 class="h5 pt-2">{{ product.title }}</h1></a>
                <div class="border">
                  <div class="col border-bottom">
                    <div class="row p-3">
                      <div class="col-6">Hardback Book</div>
                      <div class="col-6 text-end">
                        <span class="h6 fw-bold">£{{ product.price }}</span>
                      </div>
                    </div>
                  </div>
                  <div class="col">
                    <div class="row p-3">
                      <div class="col-12">
                        <label for="select{{ product.id }}">Qty</label>
                        <select id="select{{ product.id }}" class="form-select-sm align-middle">
                          <option class="fw-bold" selected>{{ item.qty }}</option>
                          <option value="">1</option>
                          <option value="">2</option>
                          <option value="">3</option>
                          <option value="">4</option>
                        </select>

                        <button type="button" id="update-button" data-index="{{ product.id }}" class="btn btn-outline-success btn-sm update-button">Update</button>
                        <button type="button" id="delete-button" data-index="{{ product.id }}" class="btn btn-outline-danger btn-sm delete-button">Delete</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endwith %}
        {% endfor %}
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault()
      var product_id = $(this).data('index')
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: '{{csrf_token}}',
          action: 'post'
        },
        success: function (json) {
          $('.product-item[data-index="' + product_id + '"]').remove()
          document.getElementById('basket_qty').innerHTML = json.qty
          document.getElementById('subtotal').innerHTML = json.subtotal
          document.getElementById('total').innerHTML = json.total
          if (json.qty == 0) {
            document.getElementById('basket_title').innerHTML = 'No Item Added on Basket'
          }
        },
        error: function (xhr, errmsg, err) {
          console.log(err)
        }
      })
    })
    
    $(document).on('click', '.update-button', function (e) {
      e.preventDefault()
      var product_id = $(this).data('index')
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_update" %}',
        data: {
          productid: $(this).data('index'),
          productqty: $('#select' + product_id + ' option:selected').text(),
          csrfmiddlewaretoken: '{{csrf_token}}',
          action: 'post'
        },
        success: function (json) {
          document.getElementById('basket_qty').innerHTML = json.qty
          document.getElementById('subtotal').innerHTML = json.subtotal
          document.getElementById('total').innerHTML = json.total
        },
        error: function (xhr, errmsg, err) {}
      })
    })
  </script>
{% endblock %}