account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .forms_auth import UserLoginForm
from django.contrib.auth.decorators import login_required
from .forms_auth import PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
    # User
    path('register/', views.account_register, name='register'),

    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name="activate"),

    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                redirect_authenticated_user=True, next_page='/account/dashboard/', form_class=UserLoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

    # Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
         success_url='password_reset_email_confirm', email_template_name='account/user/password_reset_email.html', form_class=PwdResetForm), name='pwdreset'),

    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(
        template_name="account/user/reset_status.html"), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html', success_url='/account/password_reset_complete/', form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),

    path('password_reset_complete/', TemplateView.as_view(
        template_name="account/user/reset_status.html"), name='password_reset_complete'),

    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),

    path('profile/edit/', views.edit_details, name='edit_details'),

    path('profile/delete/', views.delete_user, name='delete_user'),

    path('profile/delete_confirm/', TemplateView.as_view(
        template_name='account/user/delete_confirm.html'), name='delete_confirm'),


]

basket/urls.py
from django.urls import path
from . import views
app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name="basket_add"),
    path('update/', views.basket_update, name="basket_update"),
    path('delete/', views.basket_delete, name="basket_delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# Project Base Import for URL Settings of MEDIA
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

# Project Base URL Settings of MEDIA
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% static 'bootstrap/css/bootstrap.css' as bs_css %}
{% static 'css/main.css' as main_css %}
{% static 'js/jquery.js' as jquery_js %}
{% static 'bootstrap/js/bootstrap.bundle.js' as bs_js %}
{% static 'js/main.js' as main_js %}

<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      BookStore ||{% block title %}

      {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ bs_css }}" />
    <link rel="stylesheet" href="{{ main_css }}" />
    <script src="{{ jquery_js }}"></script>
    <script src="{{ bs_js }}"></script>
    <script src="{{ main_js }}"></script>
  </head>

  <body class="d-flex flex-column h-100">
    <header class="header">
      {% include 'header.html' %}
    </header>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <footer class="footer mt-auto">
      {% include 'footer.html' %}
    </footer>
  </body>
</html>

templates/footer.html
<div class="container">
  <div class="pt-4 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Cool stuff</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Random feature</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Team feature</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Stuff for developers</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Another one</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Last time</a>
          </li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Resource</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Resource name</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Another resource</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Final resource</a>
          </li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Team</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Locations</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Privacy</a>
          </li>
          <li class="mb-1">
            <a class="link-secondary text-decoration-none" href="#">Terms</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

templates/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid px-md-4">
    <div class="d-flex w-100 navbar-collapse">
      <a class="navbar-brand d-flex-inline" href="/">BookStore</a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Library</a>
          <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="">All</a>
            </li>
            {% for category in categories %}
              <li>
                <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name|title }} ({{ category.id }})</a>
              </li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
          </svg>
        </div>
        <span class="fs15 fw500">Shop</span>
      </button>

      {% if user.is_authenticated %}
        {% url 'account:logout' as url_logout %}
        <a type="button" role="button" href="{{ url_logout }}" class="btn btn-outline-secondary border-0 position-relative">
          <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
              <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z" />
              <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z" />
            </svg>
          </div>
          <span class="fs15 fw500">Logout</span>
        </a>
      {% else %}
        {% url 'account:login' as url_login %}

        <a type="button" role="button" href="{{ url_login }}" class="btn btn-outline-secondary border-0 position-relative">
          <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
              <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
              <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
            </svg>
          </div>
          <span class="fs15 fw500">Login</span>
        </a>
      {% endif %}

      {% url 'account:dashboard' as url_dashboard %}
      <a type="button" role="button" href="{{ url_dashboard }}" class="btn btn-outline-secondary border-0 position-relative">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
          </svg>
        </div>
        <span class="fs15 fw500">Account</span>
      </a>

      {% url 'basket:basket_summary' as url_basket_summary %}
      <a type="button" role="button" href="{{ url_basket_summary }}" class="btn btn-outline-secondary border-0 position-relative">
        {% with basket|length as total_qty %}
          <div id="basket_qty" class="basket-qty">
            {% if total_qty > 0 %}
              {{ total_qty }}
            {% else %}
              0
            {% endif %}
          </div>
        {% endwith %}

        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
          </svg>
        </div>
        <span class="fs15 fw500">Basket</span>
      </a>
    </div>
    <div class="d-md-none d-lg-none d-xl-none w-100">
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0 text-light">
          <li class="mb-1">
            <a class="dropdown-item p-2 bg-primary" href="">All</a>
          </li>
          {% for c in categories %}
            <li class="mb-1">
              <a class="dropdown-item p-2 bg-secondary" href="">{{ c.name|title }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <form class="d-flex w-100 d-md-none">
      <input class="form-control me-2" type="search" placeholder="Search products or FAQ" aria-label="Search" />
      <button class="btn btn-outline-secondary" type="submit">Search</button>
    </form>
  </div>
</nav>