basket/urls.py
from django.urls import path
from . import views
app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name="basket_add"),
    path('update/', views.basket_update, name="basket_update"),
    path('delete/', views.basket_delete, name="basket_delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# Project Base Import for URL Settings of MEDIA
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

# Project Base URL Settings of MEDIA
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category_list', kwargs={"category_slug": self.slug})


class ProductModelManager(models.Manager):
    def get_queryset(self):
        return super(ProductModelManager, self).get_queryset().filter(is_active=True)


class Product(models.Model):

    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductModelManager()

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.


def products_all(request):
    products = Product.products.all()[0:6]
    context = {'products': products}
    return render(request, 'store/home.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {
        'product': product
    })


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {
        'category': category,
        'products': products
    })

templates/store/products/category.html
{% extends '../../base.html' %}

{% block title %}
  {% if category.name %}
    {{ category.name }}
  {% else %}
    Products
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-3">
    <h3 class="h3 mb-3">Search Results for Category-" {{ category.name|title }} "</h3>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for product in products %}
        <div class="col">
          <div class="card h-100">
            <div class="card-img-top object-fit-contain overflow-hidden" style="height:225px">
              <a href="{{ product.get_absolute_url }}" class="text-decoration-none"><img src="{{ product.image.url }}" width="100%" alt="product" /></a>
            </div>
            <div class="card-body">
              <a href="{{ product.get_absolute_url }}" class="text-decoration-none d-block"><h3 class="card-title">{{ product.title }}</h3></a>
              <p class="card-text">{{ product.description|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-primary">Add to Cart</button>
                <small class="text-body-secondary">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/store/products/single.html
{% extends '../../base.html' %}
{% load static %}

{% block title %}
  {{ product.title }}
{% endblock %}

{% block content %}
  <div class="container py-3">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img src="{{ product.image.url }}" class="img-fluid mx-auto d-block" />
      </div>

      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p>
          <span class="lead">{{ product.author }}</span>
          (Author)
        </p>
        <p>{{ product.description|slice:':355' }} ...</p>

        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback</div>
              <div class="col-6 text-end">
                <span class="h4 fw-bold">£{{ product.price }}</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <div class="input-group mb-3">
                  <label class="input-group-text" for="qty_id">Qty</label>
                  <select id="qty_id" class="form-select form-select-sm">
                    <option selected value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  </select>
                </div>
              </div>
              <div class="col-6 text-end">
                <button id="add-to-basket" value="{{ product.id }}" type="button" class="btn btn-primary btn-sm">Add to Basket</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).on('click', '#add-to-basket', function (e) {
      e.preventDefault()
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_add" %}',
        data: {
          productid: $('#add-to-basket').val(),
          productqty: $('#qty_id option:selected').text(),
          csrfmiddlewaretoken: '{{csrf_token}}',
          action: 'post'
        },
        success: function (json) {
          console.log(json)
          document.getElementById('basket_qty').innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {
          console.log(err)
        }
      })
    })
  </script>
{% endblock %}